### ISSUE TITLE
Adding types and fixing bugs on TypeScript implementation

### ISSUE THREAD

**Issue by eduardoleao052** [eduardoleao052/js-torch#9]
Changes necessary in the `develop` branch before merging into `main`:
- Adding types and fixing bugs of TypeScript implementation.
- Have zero errors pop up when running `npm run check`.
- Removing `tsconfig.json` allowances before merging.

**Comment by medic-code** [comment]
@eduardoleao052 i'll work on utils.ts btw.

**Comment by eduardoleao052** [comment]
@medic-code btw, I noticed that the tests got ~30% slower after the latest PR. Is that due to `jest`?

**Comment by medic-code** [comment]
Mmm needs a bit of investigating, but the time taking in testing running is mostly due to the last test, having played around with an initial jest setup, the first two tests take around 1-2 seconds which I think is acceptable, transformer test takes around 10seconds to complete. Do you happen to have the times prior to the PR for comparison (I'm using Macbook Pro m3 btw) ?

Couple of things that do stand out for me,

1. These are most definitely integration tests which will take a longer time than unit tests, i think maybe some carefully placed mocks could help speed things up
2. The tests are a little erratic as i've had a few runs of it and they've failed because the loss went above > 0.1 (The assertion is that loss should be less than or equal to 0.1) - should we have a slightly wider criteria for loss ?

**Comment by eduardoleao052** [comment]
After initially merging into `develop`, the Transformer test was taking around 6s, and it went to ~8s with `jest`. The others increased proportionally. 

I don't think that's serious or anything, I'm just wondering if that's just due to the extra steps taken by `jest` or if the library got slightly slower in general. I'll test it out later.

And about the length of the tests: I think the `loss` threshold could be a little higher, yes. The transformer test taking longer is normal, as it is a model many times more complicated than the others, but I'll try to keep it to under 5s. Will get into it!

**Comment by eduardoleao052** [comment]
@medic-code found this online:

```

If you use TypeScript tests can take a bit longer since Jest will check types. Actually you can speed this up by skipping types checking. When you add ' { isolatedModules:true }' tests will run a bit faster. globalSetup will run every time you run 'npm run test'

```

**Comment by eduardoleao052** [comment]
Ok, sorry for spamming you :D 
I just ran the tests without `jest` and some mock functions, and it's definitely not slower. It must be because of the may we're running `jest` incorrectly as of right now.

**Comment by eduardoleao052** [comment]
@medic-code I finished correcting all the TS errors. I think I also fixed the `jest` syntax, but I ask you to make sure I didn't do anything wrong lol
Thank you so much for the work here, the package has a much more professional look to it now!

**Comment by medic-code** [comment]
Quick work on TS errors! Think the jest syntax looks fine. Good catch on type checking in jest. 

I think there's definitely room for some unit tests in the future and maybe some refactoring of these three tests (not sure whether you'd call these e2e or integration) depending on future tests, extracting the neural net creation and some of the setup for example.

**Comment by eduardoleao052** [comment]
Got it! I'll look into that soon. But now the infrastructure is in place, so it will be easier to implement.
Thank you so much again! I think I'll merge this branch into main soon, but you have any other PRs you want to add, by all means go ahead!

**Comment by medic-code** [comment]
Yep its good to have something basic in place to build from, go for it with the merge. If there's some improvements + further tests I'll open up a PR.

**Comment by medic-code** [comment]
Could you check @eduardoleao052 since merge into main, still showing up with i'm still seeing TS errors in layers.ts,tensor.ts and utils.ts ? 

<img width="508" alt="image" src="https://github.com/eduardoleao052/js-torch/assets/60046611/1ce8848b-7671-4df5-a390-a59008f20e9b">

**Comment by eduardoleao052** [comment]
@medic-code Mmmm, I'm almost sure no errors were popping up when I ran `npm run check` prior to pushing. Do you know the nature of those errors? I can't open the code right now, but will try to solve it later today. Thanks for pointing it out!

**Comment by eduardoleao052** [comment]
Got it. It's funny, because the tests even ran properly in the workflow.

What command did you execute to get this error message?

**Comment by medic-code** [comment]
In the current updated code, i did a linting check.

**Comment by eduardoleao052** [comment]
Got it. Thanks again for pointing it out!

**Comment by medic-code** [comment]
Please check incase something with my local repo is wrong. Btw with Husky and lint-staged, this wont be a problem as it will not make the commits/push whilst there are linting/type check errors.

**Comment by eduardoleao052** [comment]
That's great! I really forgot to use the `npm run lint` before pushing...
I'll check soon in my pc as well!

**Comment by medic-code** [comment]
I don't think I was being specific enough for which I apologise, no technically not errors of TS but using any as a type is quite broad and should we should try to use any very judiciously, there's usually a way to narrow this type down.

1. If you are happy to assigned but not used values, you can change this ESlint rule - this is the flexibility of eslint. I have no preference for this.
2. There is a thing called recursive types that can cover deeply nested arrays.

**Comment by eduardoleao052** [comment]
Thank you for the answers! Makes sense, I'll try to finish solving these issues then.
